-- Insert values into the table
INSERT INTO listingsAndReviews
    (
    listing_url,
    name,
    space,
    description,
    neighborhood_overview,
    notes,
    transit,
    access,
    interaction,
    house_rules,
    property_type,
    room_type,
    bed_type,
    minimum_nights,
    maximum_nights,
    cancellation_policy,
    last_scraped,
    calendar_last_scraped,
    first_review,
    last_review,
    accommodates,
    bedrooms,
    beds,
    number_of_reviews,
    bathrooms,
    price,
    amenities,
    security_deposit,
    cleaning_fee,
    extra_people,
    guests_included
    )
VALUES
<<<<<<< HEAD
        (
            'https://www.airbnb.com/rooms/1003530',
            'New York City - Upper West Side Apt',
            'Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement.',
            'Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement. New York City! Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modells (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc. Convenientl',
            'Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modells (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc.',
            'My cat, Samantha, are in and out during the summer.  The apt is layed out in such a  way that each bedroom is very private.',
            'Conveniently located near 1, 2, 3, B & C subway lines. Also buses on Columbus Avenue (downtown), Amsterdam Avenue (uptown), and Broadway (uptown/downtown). Also near origination/termination of M60 bus which goes to/from LaGuardia Airport.',
            'New York City!',
            'None',
            'No smoking is permitted in the apartment. All towels that are used should be placed in the bath tub upon departure. I have a cat, Samantha, who can stay or go, whichever is preferred.   Please text me upon departure.',
            'Apartment',
            'Private room',
            'Real Bed',
            '12',
            '360',
            'strict_14_with_grace_period',
            '2019-03-07T05:00:00.000+00:00',
            '2019-03-07T05:00:00.000+00:00',
            '2013-04-29T04:00:00.000+00:00',
            '2018-08-12T04:00:00.000+00:00',
            2,
            1,
            1,
            70,
            '1.0',
            'Internet, Wifi, Air conditioning, Kitchen, Elevator, Buzzer/wireless intercom, Heating, Family/kid friendly, Washer, Dryer',
            '135.00',
            '0.00',
            '135.00',
            '0.00',
            1
=======
    (
        'https://www.airbnb.com/rooms/1003530',
        'New York City - Upper West Side Apt',
        'Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement.',
        'Murphy bed, optional second bedroom available. Wifi available, Hulu, Netflix, TV Eat-in kitchen. Bathroom with great shower/bath.  Washer/dryer in basement. New York City! Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modells (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc. Convenientl',
        'Great neighborhood - many terrific restaurants, bakeries, bagelries. Within easy walking distance are restaurants with the cuisines from India, Thailand, Japan, China, Mexico, South America and Europe.  As well as the many small independent stores that line Broadway, there chain stores such as Urban Outfitters (clothing), Whole Foods (groceries), Sephora (cosmetics), Michaels (crafts), and Modells (sporting goods). Equidistant to Central Park and Riverside Park which have walking/running/biking trails as well as tennis and racquet ball courts. 10-15 blocks from Columbia University between Broadway and Amsterdam. The International Hostel across the street is an airport shuttle bus and double-decker tour bus stop.  The Hostel also has services available to the neighborhood such as lectures, brochures, etc.',
        'My cat, Samantha, are in and out during the summer.  The apt is layed out in such a  way that each bedroom is very private.',
        'Conveniently located near 1, 2, 3, B & C subway lines. Also buses on Columbus Avenue (downtown), Amsterdam Avenue (uptown), and Broadway (uptown/downtown). Also near origination/termination of M60 bus which goes to/from LaGuardia Airport.',
        'New York City!',
        'None',
        'No smoking is permitted in the apartment. All towels that are used should be placed in the bath tub upon departure. I have a cat, Samantha, who can stay or go, whichever is preferred.   Please text me upon departure.',
        'Apartment',
        'Private room',
        'Real Bed',
        '12',
        '360',
        'strict_14_with_grace_period',
        '2019-03-07T05:00:00.000+00:00',
        '2019-03-07T05:00:00.000+00:00',
        '2013-04-29T04:00:00.000+00:00',
        '2018-08-12T04:00:00.000+00:00',
        2,
        1,
        1,
        70,
        '1.0',
        '135.00',
        'Internet, Wifi, Air conditioning, Kitchen, Elevator, Buzzer/wireless intercom, Heating, Family/kid friendly, Washer, Dryer',
        '0.00',
        '135.00',
        '0.00',
        1
>>>>>>> 4cb92c801d870332e36a5708130ac6fe01c99397
    ),
    (
        'https://www.airbnb.com/rooms/10006546',
        'Ribeira Charming Duplex',
        'Privileged views of the Douro River and Ribeira square, our apartment offers the perfect conditions to discover the history and the charm of Porto. Apartment comfortable, charming, romantic and cozy in the heart of Ribeira. Within walking distance of all the most emblematic places of the city of Porto. The apartment is fully equipped to host 8 people, with cooker, oven, washing machine, dishwasher, microwave, coffee machine (Nespresso) and kettle. The apartment is located in a very typical area of the city that allows to cross with the most picturesque population of the city, welcoming, genuine and happy people that fills the streets with his outspoken speech and contagious with your sincere generosity, wrapped in a only parochial spirit.',
        'Fantastic duplex apartment with three bedrooms, located in the historic area of Porto, Ribeira (Cube) - UNESCO World Heritage Site. Centenary building fully rehabilitated, without losing their original character. Privileged views of the Douro River and Ribeira square, our apartment offers the perfect conditions to discover the history and the charm of Porto. Apartment comfortable, charming, romantic and cozy in the heart of Ribeira. Within walking distance of all the most emblematic places of the city of Porto. The apartment is fully equipped to host 8 people, with cooker, oven, washing machine, dishwasher, microwave, coffee machine (Nespresso) and kettle. The apartment is located in a very typical area of the city that allows to cross with the most picturesque population of the city, welcoming, genuine and happy people that fills the streets with his outspoken speech and contagious with your sincere generosity, wrapped in a only parochial spirit. We are always available to help guests',
        'In the neighborhood of the river, you can find several restaurants as varied flavors, but without forgetting the so traditional northern food. You can also find several bars and pubs to unwind after a days visit to the magnificent Port. To enjoy the Douro River can board the boats that daily make the ride of six bridges. You can also embark towards Régua, Barca dAlva, Pinhão, etc and enjoy the Douro Wine Region, World Heritage of Humanity. The Infantes house is a few meters and no doubt it deserves a visit. They abound grocery stores, bakeries, etc. to make your meals. Souvenir shop, wine cellars, etc. to bring some souvenirs.',
        'Lose yourself in the narrow streets and staircases zone, have lunch in pubs and typical restaurants, and find the renovated cafes and shops in town. If you like exercise, rent a bicycle in the area and ride along the river to the sea, where it will enter beautiful beaches and terraces for everyone. The area is safe, find the bus stops 1min and metro line 5min. The bustling nightlife is a 10 min walk, where the streets are filled with people and entertainment for all. But Porto is much more than the historical center, here is modern museums, concert halls, clean and cared for beaches and surf all year round. Walk through the Ponte D. Luis and visit the different Caves of Port wine, where you will enjoy the famous port wine. Porto is a spoken city everywhere in the world as the best to be visited and savored by all ... natural beauty, culture, tradition, river, sea, beach, single people, typical food, and we are among those who best receive tourists, confirm! Come visit us and feel at ho',
        'Transport: • Metro station and S. Bento railway 5min; • Bus stop a 50 meters; • Lift Guindais (Funicular) 50 meters; • Tuc Tuc-to get around the city; • Buses tourist; • Cycling through the marginal drive; • Cable car in Gaia, overlooking the Port (just cross the bridge).',
        'We are always available to help guests. The house is fully available to guests. We are always ready to assist guests. when possible we pick the guests at the airport.  This service transfer have a cost per person. We will also have service "meal at home" with a diverse menu and the taste of each. Enjoy the moment!',
        'Cot - 10 € / night Dog - € 7,5 / night',
        'Make the house your home...',
        'House',
        'Entire home/apt',
        'Real Bed',
        '2',
        '30',
        'moderate',
        '2019-02-16T05:00:00.000+00:00',
        '2019-02-16T05:00:00.000+00:00',
        '2016-01-03T05:00:00.000+00:00',
        '2019-01-20T05:00:00.000+00:00',
        8,
        3,
        5,
        51,
        '1.0',
        '80.00',
        'TV, Cable TV, Wifi, Kitchen, Paid parking off premise, Smoking allowed, Pets allowed, Buzzer/wireless intercom, Heating, Family/kid friendly, Washer, First Aid Kit, Fire extinguisher, Essentials, Hangers, Hair dryer, Iron, travel crib, Hot water, Bed linens, Extra pillows and blankets, Microwave, Coffee maker, Refrigerator, Dishwasher, Dishes silver, Cooking basics, Oven, Store, Cleaning before checkout, Waterfront',
        '200.00',
        '35.00',
        '15.00',
        6
);